---

- name: cisco nxos provisioning (cleanup)
  hosts: n9k 
  connection: local
  gather_facts: no

  vars:
    nxapi:
      username: admin
      password: #cisco123
      transport: nxapi
      http: no
      https: yes
      use_ssl: no
      validate_certs: no

  tasks:

  - name: configure ACL
    nxos_acl:
      name: ansible
      seq: 10
      action: permit
      proto: tcp
      src: 1.1.1.1/24
      dest: any
      state: absent
      provider: "{{ nxos_nxapi_connection }}"

  - name: remove ACL and save when modified
    nxos_config:
      lines: no ip access-list ansible
      save_when: modified
      provider: "{{ nxos_cli_connection }}"

  - name: run show ip access-list ansible
    nxos_command:
      commands: show ip access-list ansible 
      provider: "{{ nxos_cli_connection }}"

